ressource todos
	entity: todo
	path: "/todos"
	commands: delete,create,read,update
	description: "This is a ressource to save todo items"

entity todo
	title: string
	completed: boolean
	order: integer

