ressource todos
	entity: todo
	path: "/todos"
	commands: delete(all),create(all),read(all),update(all)
	description: "This is a ressource to save todo items"

entity todo
	title: string
	completed: boolean
	order: integer

role user
role admin isa user
